- name: Stop firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
