- hosts: mona-host:&k8s_cluster
  user: icspadmin
  roles:
  - common
  tags:
  - k8s-cluster-common

- hosts: mona-host:&k8s_cluster
  user: icspadmin
  roles:
  - disable-firewalld
  tags:
  - k8s-cluster-disable-firewall

- hosts: mona-host:&k8s_cluster
  user: icspadmin
  become: true
  vars:
    rke2_ha_mode: true
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
    rke2_ha_mode_keepalived: true
    rke2_api_ip : 192.168.68.79
    rke2_download_kubeconf: false
    rke2_version: v1.28.10-rc3+rke2r1
    rke2_cni: canal
    rke2_servers_group_name: 'k8s_masters'
    rke2_agents_group_name: 'k8s_workers'
    rke2_cluster_group_name: 'k8s_cluster'
  roles:
  - lablabs.rke2
  tags:
  - k8s-cluster-rke2

- hosts: mona-host:&k8s_bastion
  user: icspadmin
  become: true
  vars:
    rke_version: 1.3.2
    hostname: "rancher1.local"
    kubectl_version: "1.21.6"
    helm_version: "3.7.1"
    helmfile_version: "0.142.0"
    rancher_cli_version: "2.4.13"
    k9s_version: "0.32.4"
  roles:
  - bastion
  tags:
  - k8s-bastion

- hosts: mona-host:&k8s_bastion
  user: icspadmin
  become: true
  vars:
    rke2_api_ip : 192.168.68.70
    hostname: "rancher.local"
  roles:
  - rancher-server
  tags:
  - k8s-rancher-server

- hosts: mona-host:&k8s_proxy
  user: icspadmin
  become: true
  vars:
    - project: "dmp"
    - lan_interface: ens160
    - external_check: false
  roles:
  - haproxy
  tags:
  - k8s-proxy


# - hosts: mona-host:&k8s_workers
#   user: icspadmin
#   become: true
#   roles:
#   - rancher-worker
#   tags:
#   - k8s-rancher-worker 

