- name: Install NFS packages
  apt:
    name:
      - nfs-kernel-server
    state: present
  when: ansible_os_family == 'Debian'

- name: Install NFS packages
  yum:
    name:
      - nfs-utils
    state: present
  when: ansible_os_family == 'RedHat'

- name: Create export directory
  file:
    path: /opt/nfs/kubedata
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Configure NFS exports
  lineinfile:
    path: /etc/exports
    line: "/opt/nfs/kubedata *(rw,sync,no_subtree_check,no_root_squash)"
    create: yes

- name: Restart NFS service
  service:
    name: nfs-kernel-server
    state: restarted
  when: ansible_os_family == 'Debian'

- name: Restart NFS service
  service:
    name: nfs-server
    state: restarted
  when: ansible_os_family == 'RedHat'

